version: "3.9"

services:
  gateway:
    image: climatewatch-gateway-gateway:latest
    container_name: gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env
    depends_on:
      - weather_service
      - favorites_service
      - alerts_service

  weather_service:
    image: climatewatch-gateway-weather:latest
    container_name: weather_service
    ports:
      - "8001:8001"
    env_file:
      - ./weather_service/.env

  favorites_service:
    image: climatewatch-gateway-favorites:latest
    container_name: favorites_service
    ports:
      - "8002:8002"
    env_file:
      - ./favorites_service/.env
    volumes:
      - favorites_data:/app

  alerts_service:
    image: climatewatch-gateway-alerts:latest
    container_name: alerts_service
    ports:
      - "8003:8003"
    env_file:
      - ./alerts_service/.env

volumes:
  favorites_data:
